name: vision_assist
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.0+4
  google_mlkit_commons: ^0.9.0
  image_picker: ^1.1.2
  cupertino_icons: ^1.0.8
  flutter_compass: ^0.7.0
  google_mlkit_text_recognition: ^0.14.0 # Only use the ML Kit text recognition package
  flutter_tts: ^4.2.0
  google_mlkit_object_detection: ^0.14.0
  google_maps_flutter: ^2.7.0
  google_maps_flutter_web: ^0.5.4+3
  google_maps_webservice: ^0.0.19
  geolocator: ^13.0.2
  http: ^0.13.6
  english_words: ^4.0.0
  permission_handler: ^11.1.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
